<?php

namespace MA\PlatformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getApplicationWithAdvert()
    {
        $qb = $this->createQueryBuilder('a');// SELECT * FROM Application

        $qb->innerJoin('a.advert', 'adv')->addSelect('adv'); 
        // Mettre une limite a mes nombre de resultats
        $qb->setMaxResults($limit);
        
        return $qb->getQuery()->getResult();

    }
}
