ma_user:
    resource: "@MAUserBundle/Controller/"
    type:     annotation
    prefix:   /

ma_platform:
    resource: "@MAPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
    path: /login
    defaults:
        _controller: MAUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout